from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
import json

class ReportGenerator:
    """Generates downloadable PDF reports"""
    
    @staticmethod
    def generate_pdf(report_data, filename="health_report.pdf"):
        """Create PDF report"""
        doc = SimpleDocTemplate(filename, pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1f77b4'),
            spaceAfter=30
        )
        story.append(Paragraph("HealthAI Nexus - Medical Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Date
        date_str = datetime.now().strftime("%B %d, %Y at %I:%M %p")
        story.append(Paragraph(f"<b>Generated:</b> {date_str}", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Symptoms
        if 'symptoms' in report_data:
            story.append(Paragraph("<b>Patient Symptoms:</b>", styles['Heading2']))
            story.append(Paragraph(report_data['symptoms'], styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        # Risk Score
        if 'risk_score' in report_data:
            risk_color = colors.green if report_data['risk_score'] < 3 else colors.orange if report_data['risk_score'] < 7 else colors.red
            story.append(Paragraph(f"<b>Risk Score:</b> <font color='{risk_color.hexval()}'>{report_data['risk_score']}/10</font>", styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
        
        # Synthesis
        if 'synthesis' in report_data:
            story.append(Paragraph("<b>Medical Assessment:</b>", styles['Heading2']))
            story.append(Paragraph(report_data['synthesis'], styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        # Evidence
        if 'evidence' in report_data:
            story.append(Paragraph("<b>Evidence-Based Information:</b>", styles['Heading2']))
            story.append(Paragraph(report_data['evidence'], styles['Normal']))
            story.append(Spacer(1, 0.2*inch))
        
        # Specialist Reports
        if 'specialist_reports' in report_data:
            story.append(Paragraph("<b>Specialist Consultations:</b>", styles['Heading2']))
            for specialist, report in report_data['specialist_reports'].items():
                story.append(Paragraph(f"<b>{specialist.title()}:</b>", styles['Heading3']))
                story.append(Paragraph(str(report)[:500], styles['Normal']))
                story.append(Spacer(1, 0.1*inch))
        
        # Disclaimer
        story.append(Spacer(1, 0.3*inch))
        disclaimer = """<i>Disclaimer: This report is generated by AI and is for informational purposes only. 
        It does not constitute medical advice. Please consult with a qualified healthcare provider for proper diagnosis and treatment.</i>"""
        story.append(Paragraph(disclaimer, styles['Normal']))
        
        doc.build(story)
        return filename
    
    @staticmethod
    def save_json(report_data, filename="health_report.json"):
        """Save report as JSON"""
        with open(filename, 'w') as f:
            json.dump(report_data, f, indent=2)
        return filename
